# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 058d4a4bd877529bfa7d6d472241b2bac65d2b78c44e03a05d2e7288cff2c967309d0cd1d9503e2d8872975e3e2e55ca6ef5703859d9b78b3f731b1cad86be71

test:
  secret_key_base: 1f48d3f403de7e3c35952e1db2004a392dd3c612641f795b3ef8754f1c6d4c951dcba7c5376ec61a2bccbfc9ac6130d20c2b70973350b00b49614fc77f5459ef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
